[package]
name = "wowp-rust"
version = "0.1.0"
authors = ["Ryan Park <admin@ryanpark.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.3"
regex = "1.3.4"
nom = "5.1.1"
rayon = "1.3.0"